name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - uses: cargo-bins/cargo-binstall@main

      - name: Install just and dioxus-cli
        run: cargo binstall -y just dioxus-cli

      - name: Lint, test, build
        run: just ci
        env:
          DX_BIN: dx
